import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ThemeProvider from "@/components/common/Theme-Provider";
// import AuthProvider from "@/components/common/Auth-Provider";
import { getServerSession } from "next-auth";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "600"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* <AuthProvider> */}
          <ThemeProvider>
            <div className="bg-richWhite dark:bg-richBlack text-richBlack dark:text-richWhite w-full min-h-screen flex justify-center items-center">
              {children}
            </div>
            <ToastContainer />
          </ThemeProvider>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
